Update to avoid compiling error in Arduino 2.2
Changes to avoid compiling errors in Arduino 2.2

avoids WIFI errors in current Arduino version 
e.g.: error: 'union arduino_event_info_t' has no member named 'disconnected'; did you mean 'eth_connected'?
   Serial.println(info.disconnected.reason);

Note:
it is not necessary to add the library "ESP32 BLE for Arduino"
BLE library is included in Arduino 2.2